### ISSUE TITLE
Maven update

### ISSUE THREAD

**Issue by mausch** [adorepump/chocolatey-packages#25]
The current Maven package at https://chocolatey.org/packages/maven throws an error when trying to download version 3.2.3. This is because the selected Apache mirror apparently deletes old versions quite quickly. I see that @MichaelPereira has changed the mirror in https://github.com/MichaelPereira/chocolatey-packages/commit/95c6a6f48704bc8ee363fee1d42ee6967abd204b , is there any chance you could pull that and publish it to chocolatey.org?

Thanks

**Comment by MichaelPereira** [comment]
I can do it without having to merge the PR. I will set a reminder for tomorrow noon.

**Comment by MichaelPereira** [comment]
The package was update to 3.2.5 on chocolatey.

**Comment by mausch** [comment]
Many thanks!
